"""Tests for Amenity API endpoints"""
import unittest
from app import create_app, db
from app.models.amenity import Amenity


class TestAmenityEndpoints(unittest.TestCase):
    """Test cases for Amenity API"""
    
    @classmethod
    def setUpClass(cls):
        """Set up test fixtures"""
        cls.app = create_app("config.TestingConfig")
        cls.client = cls.app.test_client()
        
        with cls.app.app_context():
            db.create_all()
    
    @classmethod
    def tearDownClass(cls):
        """Clean up after tests"""
        with cls.app.app_context():
            db.drop_all()
    
    def test_get_amenities_returns_200(self):
        """Test GET /api/v1/amenities/ returns 200"""
        response = self.client.get('/api/v1/amenities/')
        self.assertEqual(response.status_code, 200)
        self.assertIsInstance(response.json, list)
    
    def test_get_nonexistent_amenity_returns_404(self):
        """Test GET /api/v1/amenities/<id> returns 404 for invalid ID"""
        response = self.client.get('/api/v1/amenities/nonexistent-id')
        self.assertEqual(response.status_code, 404)
    
    def test_create_amenity_requires_auth(self):
        """Test POST /api/v1/amenities/ requires authentication"""
        response = self.client.post('/api/v1/amenities/',
            json={"name": "Swimming Pool"},
            content_type='application/json'
        )
        self.assertEqual(response.status_code, 401)
    
    def test_update_amenity_requires_auth(self):
        """Test PUT /api/v1/amenities/<id> requires authentication"""
        response = self.client.put('/api/v1/amenities/some-id',
            json={"name": "Updated Amenity"},
            content_type='application/json'
        )
        self.assertEqual(response.status_code, 401)


class TestAmenityModel(unittest.TestCase):
    """Test cases for Amenity model"""
    
    @classmethod
    def setUpClass(cls):
        """Set up test fixtures"""
        cls.app = create_app("config.TestingConfig")
    
    def test_amenity_creation(self):
        """Test Amenity model can be instantiated"""
        with self.app.app_context():
            amenity = Amenity(name="WiFi")
            self.assertEqual(amenity.name, "WiFi")
            # ID is generated by BaseModel __init__
            db.session.add(amenity)
            db.session.flush()
            self.assertIsNotNone(amenity.id)
            db.session.rollback()
    
    def test_amenity_has_timestamps(self):
        """Test Amenity has created_at and updated_at after save"""
        with self.app.app_context():
            amenity = Amenity(name="Air Conditioning Test")
            db.session.add(amenity)
            db.session.flush()
            self.assertIsNotNone(amenity.created_at)
            self.assertIsNotNone(amenity.updated_at)
            db.session.rollback()


if __name__ == '__main__':
    unittest.main()
